#!/bin/zsh

# Detect build architecture
arch=$(uname -m)
if [[ $arch == x86_64 ]]; then
    echo -e "\e[1;91mConfiguring for Intel\e[0m"
elif [[ $arch == arm64 ]]; then
    echo -e "\e[1;91mConfiguring for Apple Silicon\e[0m"
fi

# Configure
autoreconf -fi
./configure
