name: Build and Test
on:
  push:
    branches:
      - main
      - branch-*
    paths-ignore:
      - 'CONTRIBUTORS'
      - 'NEWS'
      - 'README.md'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - branch-*
    paths-ignore:
      - 'CONTRIBUTORS'
      - 'NEWS'
      - 'README.md'

env:
  APT_PACKAGES: libtool libtool-bin automake autoconf libssl-dev libgcrypt-dev libkrb5-dev libpam0g-dev libdb-dev libtdb-dev libmysqlclient-dev libavahi-client-dev libacl1-dev libcrack2-dev libcups2-dev tcpd

jobs:
  build:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install --assume-yes --no-install-recommends ${{ env.APT_PACKAGES }}
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: ./configure
      - name: Make
        run: make -j $(nproc)
      - name: Run tests
        run: make check
      - name: Run distribution tests
        run: make distcheck
