name: macos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v3
    - run: brew upgrade
    - run: brew install dbus meson mysql dbus-glib libressl
    - run: meson build
    - run: ninja -C build
