name: macos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
    - uses: actions/checkout@v3
    - run: brew install dgsga/netatalk-dbus/dbus-glib docbook-xsl libressl meson mysql
    - run: meson setup build
    - run: ninja -C build
